
INSERT INTO blogful_articles (title, date_published, content)
VALUES
    ('Article1', now() - '21 days'::INTERVAL, 'Lorem ipsum dolor sit amet, cum in utinam eruditi elaboraret, et duo delicata adolescens. Sit et alia deserunt mandamus, ex per meis repudiare. No sea esse diceret. Tollit graeco percipit ne nam. Vel patrioque percipitur comprehensam in, ei vis vidisse labitur consulatu. Cu mel meis aperiam temporibus, sed ei ignota utroque sapientem. Mei lorem liber soluta ex, sensibus inciderint cotidieque an duo. Nostrum invenire eu sea, facilisi salutandi ut vis. Id eum natum ipsum nominavi, oratio maiorum ne vis, ius ea error tollit dignissim. Duo ut munere utroque apeirian, vel habemus'),  
    ('Article2', now() - '21 days'::INTERVAL,'Lorem ipsum dolor sit amet, cum in utinam eruditi elaboraret, et duo delicata adolescens. Sit et alia deserunt mandamus, ex per meis repudiare. No sea esse diceret. Tollit graeco percipit ne nam. Vel patrioque percipitur comprehensam in, ei vis vidisse labitur consulatu.'),
    ('Article3', now() - '21 days'::INTERVAL,'Lorem ipsum dolor sit amet, cum in utinam eruditi elaboraret, et duo delicata adolescens. Sit et alia deserunt mandamus, ex per meis repudiare. No sea esse diceret. Tollit graeco percipit ne nam. Vel patrioque percipitur comprehensam in, ei vis vidisse labitur consulatu.'),
    ('Article4', now() - '9 days'::INTERVAL,'Cu mel meis aperiam temporibus, sed ei ignota utroque sapientem. Mei lorem liber soluta ex, sensibus inciderint cotidieque an duo. Nostrum invenire eu sea, facilisi salutandi ut vis. Id eum natum ipsum nominavi, oratio maiorum ne vis, ius ea error tollit dignissim. Duo ut munere utroque apeirian, vel habemus'),
    ('Article5', now() - '9 days'::INTERVAL,'Cu mel meis aperiam temporibus, sed ei ignota utroque sapientem. Mei lorem liber soluta ex, sensibus inciderint cotidieque an duo. Nostrum invenire eu sea, facilisi salutandi ut vis. Id eum natum ipsum nominavi, oratio maiorum ne vis, ius ea error tollit dignissim. Duo ut munere utroque apeirian, vel habemus'),
    ('An article about dogs', now() - '9 days'::INTERVAL,''),  
    ('An article about dragons', now() - '7 days'::INTERVAL,''),
    ('Your loss - is it? really', now() - '7 days'::INTERVAL,'Cu mel meis aperiam temporibus, sed ei ignota utroque sapientem. Mei lorem liber soluta ex, sensibus inciderint cotidieque an duo. Nostrum invenire eu sea, facilisi salutandi ut vis. Id eum natum ipsum nominavi, oratio maiorum ne vis, ius ea error tollit dignissim. Duo ut munere utroque apeirian, vel habemus'),
    ('Coming out of quarantine', now() - '5 days'::INTERVAL,''),
    ('Antichovies are gross', now() - '5 days'::INTERVAL,''),
    ('How many miles should you run?',now() - '5 days'::INTERVAL,''),
    ('Busy work and what it does to the pscyhe', now() - '5 days'::INTERVAL,''),
    ('People just being lazy and trying to come off as not', now() - '4 days'::INTERVAL,''),
    ('Own your shit', now() - '4 days'::INTERVAL,''),
    ('Focus on the good', now() - '4 days'::INTERVAL,''),
    ('Moving on to better things',  now() - '3 days'::INTERVAL,''),
    ('Life now and then',now() - '3 days'::INTERVAL,''),
    ('what?! you did what', now() - '3 days'::INTERVAL,'Tollit graeco percipit ne nam. Vel patrioque percipitur comprehensam in, ei vis vidisse labitur consulatu. Cu mel meis aperiam temporibus, sed ei ignota utroque sapientem. Mei lorem liber soluta ex, sensibus inciderint cotidieque an duo. Nostrum invenire eu sea, facilisi salutandi ut vis. '),
    ('Fried Trickin',now() - '3 days'::INTERVAL,''),
    ('Love is the answer', now() - '3 days'::INTERVAL,'Tollit graeco percipit ne nam. Vel patrioque percipitur comprehensam in, ei vis vidisse labitur consulatu. Cu mel meis aperiam temporibus, sed ei ignota utroque sapientem. Mei lorem liber soluta ex, sensibus inciderint cotidieque an duo. Nostrum invenire eu sea, facilisi salutandi ut vis. '),
    ('Everyone has their own story',  now() - '2 days'::INTERVAL,''),
    ('Spring is in the Air',  now() - '2 days'::INTERVAL,''),
    ('Music Soothes the Soul', now() - '2 days'::INTERVAL,''),
    ('Pumpkin Pie will save your well-being', now() - '1 days'::INTERVAL,''),
    ('Did you really eat that', now(),'Tollit graeco percipit ne nam. Vel patrioque percipitur comprehensam in, ei vis vidisse labitur consulatu. Cu mel meis aperiam temporibus, sed ei ignota utroque sapientem. Mei lorem liber soluta ex, sensibus inciderint cotidieque an duo. Nostrum invenire eu sea, facilisi salutandi ut vis. '),
    ('Beer is what''s for dinner', now(),'Tollit graeco percipit ne nam. Vel patrioque percipitur comprehensam in, ei vis vidisse labitur consulatu. Cu mel meis aperiam temporibus, sed ei ignota utroque sapientem. Mei lorem liber soluta ex, sensibus inciderint cotidieque an duo. Nostrum invenire eu sea, facilisi salutandi ut vis. '),
    ('Don''t go bacon my heart', now(),'')
;
